# Generated by Django 4.2.3 on 2023-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
